apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: es-client
  namespace: ump-es-staging
  labels:
    type: client
    component: es-client
spec:
  replicas: 2
  template:
    metadata:
      labels:
        type: client
        component: es-client
    spec:
      securityContext:
          fsGroup: 0
      containers:
      - name: elasticsearch-client
        env:
        - name: SERVICE
          value: "es-cluster"
        - name: ES_JAVA_OPTS
          value: "-Xms1g -Xmx1g"
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NODE_DATA
          value: "false"
        - name: NODE_MASTER
          value: "false"
        resources:
          requests:
            cpu: "4"
            memory: "8Gi"
          limits:
            cpu: "4"
            memory: "8Gi"
        image: "fabric8/elasticsearch-k8s:2.3.2"
        imagePullPolicy: "Always"
        ports:
        - containerPort: 9200
          name: http
        - containerPort: 9300
          name: transport
