apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "es-master"
  namespace: ump-es-staging
  labels:
    type: master
    component: es-cluster
spec:
  replicas: 3
  template:
    metadata:
      labels:
        type: master
        component: es-cluster
    spec:
      securityContext:
          fsGroup: 0
      containers:
      - name: elasticsearch
        env:
        - name: SERVICE
          value: "es-cluster"
        - name: ES_JAVA_OPTS
          value: "-Xms2g -Xmx2g"
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NODE_DATA
          value: "false"
        resources:
          requests:
            cpu: "4"
            memory: "8Gi"
          limits:
            cpu: "4"
            memory: "8Gi"
        image: "fabric8/elasticsearch-k8s:2.3.2"
        imagePullPolicy: "Always"
        ports:
        - containerPort: 9300
          name: transport
