apiVersion: v1
kind: Service
metadata:
  name: kibana-logging
  namespace: kchitta
  labels:
    k8s-app: kibana-logging
    kubernetes.io/cluster-service: "false"
    kubernetes.io/name: "Kibana"
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5601
    protocol: TCP
  selector:
    k8s-app: kibana-logging
