---
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    k8s-app: kibana-logging
    kubernetes.io/cluster-service: "false"
    version: v1
  name: kibana-logging-v1
  namespace: kchitta
spec:
  replicas: 1
  selector:
    k8s-app: kibana-logging
    version: v1
  template:
    metadata:
      labels:
        k8s-app: kibana-logging
        kubernetes.io/cluster-service: "false"
        version: v1
    spec:
      containers:
        -
          env:
            -
              name: ELASTICSEARCH_URL
              value: "http://10.148.4.191:9200"
          image: "kibana:5.1.1"
          imagePullPolicy: Always
          name: kibana-logging
          ports:
            -
              containerPort: 5601
              name: ui
              protocol: TCP
          resources:
            limits:
              cpu: 1000m
              memory: 2048Mi
