---
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    k8s-app: demo-app
    kubernetes.io/cluster-service: "false"
    version: v1
  name: demo-app
spec:
  replicas: 1
  selector:
    k8s-app: demo-app
    version: v1
  template:
    metadata:
      labels:
        k8s-app: demo-app
        kubernetes.io/cluster-service: "false"
        version: v1
    spec:
      containers:
        -
          env:
            -
              name: ELASTIC_URL
              value: "http://10.147.5.86:9200"
          image: "ecr.vip.ebayc3.com/kchitta/demotest:1.0"
          imagePullPolicy: Always
          name: demo-app
          resources:
            limits:
              cpu: 1000m
              memory: 2048Mi
